name: .NET Core

on: 
  push:
    branches: archna
    paths: [apis/poi/**,.github/workflows/workflowarchna.yml]
  pull_request:
    branches: master
    paths: [apis/poi/**,.github/workflows/workflowarchna.yml]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.301
    - name: Install dependencies
      run: dotnet restore apis/poi/web/poi.csproj
    - name: Build
      run: dotnet build --configuration Release --no-restore apis/poi/web/poi.csproj
    - name: Test
      run: dotnet test --no-restore --verbosity normal #apis/poi/tests/UnitTests/UnitTests.csproj 
    - name: Open Github Issue
      if: failure()
        # You may pin to the exact commit or the version.
        # uses: alialaa/issue-action@16298c378572dac709364a3b2de16acb02efdc10
      uses: alialaa/issue-action@v1.0.0
      with:
        # Github Token
        token: 45becacca90b93bc3e45681e3f09f473c130312b
        # Issue Title
        title: build failed
        # Issue Body
        body: build failed
        # Issue Assignees
        assignees: buvananaji
